language: node_js
install:
  - yarn install
script:
  - yarn lint
  - yarn build
  - yarn build:binaries
  - yarn test
node_js:
  - '10'
  - '12'
  - '14'
after_success:
  - yarn release
  - npx ci-scripts slack
  - npx ci-scripts github-post
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
